version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOSTNAME: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: photo_study_clone
#      postgresql+psycopg2://admin:12345678@localhost:5432/photo_study_clone
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
#      - "${POSTGRES_PORT}:5432"
    volumes:
      - /home/thanhnc/docker_data/photo_study_clone:/var/lib/postgresql/data/
