version: "3.3"

services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "${POSTGRES_PORT}:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: ${FLASK_ENV}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: SECRET_KEY
    command: flask run --host 0.0.0.0 --port 5001
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "5000:5000"
#volumes:
#  pgdata: